### ISSUE TITLE
Question: What is the difference between JASPER and JARVIS project ?

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#133]
I discovered it in the same time at yours. But that can be usefull to know the difference :)

1- Jasper is using only English language

2- After ? :)

**Comment by alexylem** [comment]
To be honest I build Jarvis because I was frustrated trying to install & use Jasper in French... The whole idea of Jarvis was (and still is) to propose something super easy to install & to use in multiple languages, from the selection/installation of voice recognition/speech engines to the definition of simple commands.
I let you make you own opinion, if someone from Jasper team sees this, feel free to make a quick comparison 😄

**Comment by YuukanOO** [comment]
I personnally like jarvis because it uses shell commands to get jobs done and I think it is some kind of a killer feature. With this system, you can plug anything you want as long as it runs under Linux.
