### ISSUE TITLE
Embed README.md as plugin description on the Store + multilanguage?

### ISSUE THREAD

**Issue by kevincaradant** [alexylem/jarvis#175]
HI @alexylem 

I create an issue here instead of continue in the pull request of Jarvis-plugin because that can be usefull for others.

I created a directory `fr` and `en` in my plugin. 

But I have only one readme  in french for both folders.

Should I have to put two readme file in the `fr` and `en` folder maybe ? 

Also, how your store manage the plugin repository if I add a language folder "en" in my case after have to created the plugin in your store ? Is it a problem or have I to do something ? 

Thank you, I hope understand this time :)

**Comment by alexylem** [comment]
Fow now I don't know how to handle multi-language plugin descriptions.
Actually the README.md is not even supposed (for now) to contain your plugin description (should be on the store).
However, i'm working to be able to embed the README.md directly in the store (so that you have full control on the plugin description & be able to update it at any time).
Will use this issue to track progress on that.
So for now keep only 1 README.me at root of your repo.

To answer your second question, there is no re-submission needed. Your repo is yours, so do anything you want with it 😄  Add any language folders you want, it will be directly usable from Jarvis!

Alex.

**Comment by kevincaradant** [comment]
`To answer your second question, there is no re-submission needed. Your repo is yours, so do anything you want with it :smile: Add any language folders you want, it will be directly usable from Jarvis!`

OK perfect, thank you :). I will follow your progress here. Good luck

**Comment by alexylem** [comment]
Progressing well, I can now embed the `README.md` directly from Github into the WebStore, I just need to find out how to render the `markdown` now (formatting, links...):
![image](https://cloud.githubusercontent.com/assets/11017174/19303261/43f7642a-9068-11e6-9610-d6c4b893e6dc.png)

**Comment by alexylem** [comment]
Now properly rendered:
![image](https://cloud.githubusercontent.com/assets/11017174/19306370/a433c07e-9075-11e6-970a-494c28897728.png)

I will replace the plugin description page layout to display the repo's `README.md` instead. I have to do pull requests on all repos to move their plugin Description there...
