### ISSUE TITLE
Comments on plugins

### ISSUE THREAD

**Issue by alexylem** [alexylem/jarvis#293]
### Description

There are a lot of comments published by users about plugins on the site. As plugins can be posted anonymously, the authors are not informed about the issues raised by people.

Two options:
- Make account mandatory to publish plugins, and get notified on comments from users of own plugins
- Reinforce usage of github ticket, but comments must remain opened for plugin rating...

**Comment by Jean-Bernard-Hallez** [comment]
Ha oui excellente idée... perso je préfère l'option 1....

**Comment by byackee** [comment]
je préfère l'option 2 moi :) c'est plus simple de gérer les issues sur une seule plateforme

**Comment by alexylem** [comment]
Je suis assez d'accord avec @byackee (je pense même à fermer Disqus pour cette raison).

Pour le moment j'ai changé la publication des plugins pour qu'un compte soit obligatoire.
Ca me permet de notifier la personne pour les commentaires (je viens de le mettre en place ca fonctionne). A tous ceux qui on publié des plugins, si vous l'avez fait de manière anonyme merci de me communiquer votre compte domotiquefacile et le plugin en question afin que je les associe. Cela vous permettra en outre de modifier votre plugin (URL du repo, image, tags...).

J'ai aussi rajouté une indication au dessus du formulaire des commentaires:
![image](https://cloud.githubusercontent.com/assets/11017174/21286543/554f8536-c457-11e6-91a3-971e48ff66b5.png)

**Comment by Jean-Bernard-Hallez** [comment]
OK parfait... tous les chemins mènent à Rome le principal c'est que tout le monde soit content.... 


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Alexandre Mély <notifications@github.com> 
Date : 17/12/2016  12:50  (GMT+01:00) 
À : alexylem/jarvis <jarvis@noreply.github.com> 
Cc : Hallez <jbhallez@aol.com>, Comment <comment@noreply.github.com> 
Objet : Re: [alexylem/jarvis] Comments on plugins (#293) 

Je suis assez d'accord avec @byackee (je pense même à fermer Disqus pour cette raison).
Pour le moment j'ai changé la publication des plugins pour qu'un compte soit obligatoire.

Ca me permet de notifier la personne pour les commentaires (je viens de le mettre en place ca fonctionne). A tous ceux qui on publié des plugins, si vous l'avez fait de manière anonyme merci de me communiquer votre compte domotiquefacile et le plugin en question afin que je les associe. Cela vous permettra en outre de modifier votre plugin (URL du repo, image, tags...).
J'ai aussi rajouté une indication au dessus du formulaire des commentaires:



—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexylem/jarvis","title":"alexylem/jarvis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alexylem/jarvis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexylem in #293: Je suis assez d'accord avec @byackee (je pense même à fermer Disqus pour cette raison).\r\n\r\nPour le moment j'ai changé la publication des plugins pour qu'un compte soit obligatoire.\r\nCa me permet de notifier la personne pour les commentaires (je viens de le mettre en place ca fonctionne). A tous ceux qui on publié des plugins, si vous l'avez fait de manière anonyme merci de me communiquer votre compte domotiquefacile et le plugin en question afin que je les associe. Cela vous permettra en outre de modifier votre plugin (URL du repo, image, tags...).\r\n\r\nJ'ai aussi rajouté une indication au dessus du formulaire des commentaires:\r\n![image](https://cloud.githubusercontent.com/assets/11017174/21286543/554f8536-c457-11e6-91a3-971e48ff66b5.png)\r\n"}],"action":{"name":"View Issue","url":"https://github.com/alexylem/jarvis/issues/293#issuecomment-267758636"}}}
