### ISSUE TITLE
JSON answer : fixed key instead of hotword?

### ISSUE THREAD

**Issue by Oliv4945** [alexylem/jarvis#564]
@alexylem, I just understood [an issue](https://github.com/Oliv4945/jarvis-android-app/issues/9#issuecomment-297397216) with the app: I thought that the generated JSON always have the same key (`Jarvis`) for the answer but after digging [into the code](https://github.com/alexylem/jarvis/blob/0e192cbf44251176376bc1b7d0f8ff741e758896/utils/utils.sh#L113) I see that the key is the hotword.

I think it is not a good practice to have a variable key in a JSON file: only the content should change, not the key. So I propose to set the key to `Jarvis` or `answer` instead.

Obviously if you do not agree I will update the app to query the hotword and use it as the key :-).

**Comment by alexylem** [comment]
Good point, the reason I used the trigger is to display properly the answer in Jarvis-UI plugin. Here is how I parse the answer in javascript:
```js
my.post({
        url: ractive.get ('server_url'),
        data: JSON.stringify (data),
        success: function (messages) {
            $.each (messages, function () {
                $.each (this, function (key, text) {
                    ractive.addMessage (key, text);
                });
            });
            $(".panel-body").animate({ scrollTop: 9999 });
        }
    });
```
So for each key value pair, I write the `key`, then `: ` then the `value`. This way I can also output troubleshooting information:
![image](https://cloud.githubusercontent.com/assets/11017174/25439328/7356cd72-2a9c-11e7-91c0-2f3d2a16fb4a.png)
Now for the coloring, in the `addmessage` I test the key=
```js
addMessage: function (key, text) {
        switch (key) {
            case 'debug':
            case 'warning':
            case 'error':
                type=key;
                break;
            case 'You':
                type='you';
                break;
            default:
                type="jarvis";
        }
        this.push ('messages', {
            type: type,
            key: key,
            text: text
        });
```
So if not debug, warning or error, I assume it's Jarvis' name so I color it this way (whatever Jarvis name is).
I know could be better by retrieving the trigger name upfront, it was a lazy approach to avoid a call but I can change if needed.

**Comment by Oliv4945** [comment]
>So if not debug, warning or error, I assume it's Jarvis' name so I color it this way (whatever Jarvis name is).

Ok

>I know could be better by retrieving the trigger name upfront, it was a lazy approach to avoid a call but I can change if needed.

I will not blame you for being lazy, I am too :)
But, as you already get `action=get_config` when the page is loaded, it should be really fast to change

Nevertheless I implemented a call to the config and it works: the app will be compatible in next release, so now this issue is just to improve jarvis-core/api code, I let you close the issue if you choose not to do it :-)

**Comment by alexylem** [comment]
Shit you are right, I'm already doing the call anyway...
https://github.com/alexylem/jarvis-ui/blob/master/js/my.js#L255
then I'll change it as suggested 👍

**Comment by Oliv4945** [comment]
:-)

Do you plan to do it soon or in few weeks ? Just to now if I release the
Android app tonight with a patch to use the trigger word or I wait a bit.

**Comment by alexylem** [comment]
Let me just check quickly if this will not break the integration with android wear / tasker that is parsing this JSON already...

**Comment by alexylem** [comment]
@Jean-Bernard-Hallez si tu passes par la on envisage avec @Oliv4945 de changer le retour de Jarvis API de:
```json
[{"Jarvis":"Bonjour"}]
```
par
```json
[{"answer":"Bonjour"}]
```
J'imagine que ca va impacter [ta procédure](https://github.com/Jean-Bernard-Hallez/jarvis-testjb/blob/master/Jarvis%20et%20son%20t%C3%A9l%C3%A9phone%20ou%20tablette.pdf) pour avoir le retour en synthèse vocale sur une montre android wear. Mais ca pourrait aussi la simplifier dans le sens ou la clé sera toujours "`answer`" et non pas le hotword de l'utilisateur qui peut varier.
Qu'en penses-tu? Serais-tu prêt à faire la modif dans ta procédure?

**Comment by Oliv4945** [comment]
On va attendre l'avis de Jean-Bernard mais il y a `Fields: jarvis()` donc a
priori il y a le même problème que ce que j'ai rencontré, qui sera résolu
en changeant pour "answer".

Pour l'appli je vais essayer d'intégrer les champs "trigger" ou "answer"
comme ça la bascule se fera en douceur

**Comment by Oliv4945** [comment]
Ok, c'est fait: dans la [v0.1.4](https://github.com/Oliv4945/jarvis-android-app/releases/tag/v0.1.4), il y a une sélection du hotword ou "answer" pour avec une bascule transparente lors de ta mise à jour.

**Comment by alexylem** [comment]
Ok je te tiens au courant quand j'ai fait la modif suite à la confirmation de @Jean-Bernard-Hallez

**Comment by Jean-Bernard-Hallez** [comment]
Je ne suis pas devant mon ordinateur ok je modifierai en fonction de ce que tu auras fait.. 


Envoyé depuis mon appareil Samsung

-------- Message d'origine --------
De : Alexandre Mély <notifications@github.com> 
Date : 27/04/2017  08:18  (GMT+01:00) 
À : alexylem/jarvis <jarvis@noreply.github.com> 
Cc : Hallez <jbhallez@aol.com>, Mention <mention@noreply.github.com> 
Objet : Re: [alexylem/jarvis] JSON anwer : fixed key instead of hotword ?
  (#564) 

Ok je te tiens au courant quand j'ai fait la modif suite à la confirmation de @Jean-Bernard-Hallez

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/alexylem/jarvis","title":"alexylem/jarvis","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/alexylem/jarvis"}},"updates":{"snippets":[{"icon":"PERSON","message":"@alexylem in #564: Ok je te tiens au courant quand j'ai fait la modif suite à la confirmation de @Jean-Bernard-Hallez "}],"action":{"name":"View Issue","url":"https://github.com/alexylem/jarvis/issues/564#issuecomment-297622192"}}}

**Comment by Oliv4945** [comment]
@alexylem It works well in Jarvis-ui and Android app, thanks ! :+1:

**Comment by Jean-Bernard-Hallez** [comment]
Bonjour... un peu absent en ce moment mais je viens de mettre à jour le project Jarvis+Tasker...

**Comment by alexylem** [comment]
@Jean-Bernard-Hallez merci!!
